apiVersion: v1
kind: Pod
metadata:
  name: service1
  labels:
    app: service1
spec:
  containers:
    - name: service1
      image: ghcr.io/cloudnativecheetsheet/service1:latest
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
---    
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080