apiVersion: v1
kind: Pod
metadata:
  name: service1
  labels:
    app: service1
spec:
  containers:
    - name: service1
      image: registry.gitlab.com/keisuke.sakasai/otel-sample-app-zenn:service1
      ports:
        - containerPort: 8080
      imagePullPolicy: Always
---    
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080